spring:
  application:
    name: digital-wallet
  threads:
    virtual:
      enabled: true
  datasource:
    hikari:
      transaction-isolation: 8
      connection-timeout: 5000
      maximum-pool-size: 30
  jpa:
    hibernate:
      ddl-auto: validate
  jackson:
    default-property-inclusion: non_null
    deserialization:
      FAIL_ON_UNKNOWN_PROPERTIES: false
      ACCEPT_FLOAT_AS_INT: false
    mapper:
      ACCEPT_CASE_INSENSITIVE_PROPERTIES: true
      ACCEPT_CASE_INSENSITIVE_ENUMS: true
    date-format: com.fasterxml.jackson.databind.util.StdDateFormat
  flyway:
    enabled: true
    locations: classpath:db/migration/postgresql
